name: 'Checkout Branch'
description: 'Checks out the branch and prints its name'
inputs:
  branch:
    description: 'Branch to checkout'
    required: true
outputs:
  current-branch:
    description: 'The name of the checked out branch'
    value: ${{ steps.get-branch.outputs.branch }}  # Set the output value correctly

runs:
  using: 'composite'
  steps:
    # - name: Checkout the branch
    #   uses: actions/checkout@v3
    #   with:
    #     ref: ${{ inputs.branch }}

    - name: Get current branch name
      id: get-branch
      run: |
        echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
        echo "branch=${{ env.branch }}" >> $GITHUB_OUTPUT  # Set the output correctly
        echo "Checked out branch: ${{ inputs.branch }}"
      shell: bash  # Ensure this line is present
