name: 'Checkout Branch'
description: 'Checks out the branch and prints its name'
inputs:
  branch:
    description: 'Branch to checkout'
    required: true
outputs:
  current-branch:
    description: 'The name of the checked out branch'
    value: ${{ steps.get-branch.outputs.branch }}  # Set the output value correctly

runs:
  using: 'composite'
  steps:
    - name: The current branch running job is ${{ inputs.branch }}"
      run: echo " The current branch running job is: 
    # - name: Checkout the branch
    #   uses: actions/checkout@v3
    # Manually check out the branch using git
    - name: Checkout the branch
      run: |
        git branch
        git checkout ${{ inputs.branch }}
        echo "Checked out branch: ${{ inputs.branch }}"
      shell: bash
    - name: Get current branch name
      id: get-branch
      run: |
        echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
        echo "branch=${{ env.branch }}" >> $GITHUB_OUTPUT  # Set the output correctly
        echo "Checked out branch: ${{ inputs.branch }}"
      shell: bash  # Ensure this line is present
