{{- if .Values.ingress.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iap-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: iap-cluster-secretstore
  target:
    name: iap-client-secret # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "iap-secret"  # name of the GCPSM secret
{{ end }}
