{{- if .Values.ingress.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "main-helm.chartName" . }}-ingress-frontend-config
  namespace: {{ .Release.Namespace }}
spec:
  redirectToHttps:
    enabled: true
{{ end }}
