{{- if .Values.ingress.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "main-helm.chartName" . }}-ingress-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 3600
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthcheck
    port: {{ .Values.deployment.containerPort }}
  iap:
    enabled: {{ .Values.ingress.iap }}
    oauthclientCredentials:
      secretName: iap-client-secret
  {{- if .Values.ingress.securityPolicy }}
  securityPolicy:
    name: {{ .Values.ingress.securityPolicy }}
  {{- end }}
{{ end }}
