{{- if .Values.secrets.enabled }}
{{ $secretStoreRef := printf "%s-secrets-store" .Values.environment.service_name | quote }}
{{ $target := .Values.environment.service_name | quote }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "main-helm.chartName" . }}
spec:
  data:
    {{- range $secret_env_name, $secret_key := .Values.secrets.env  }}
    - remoteRef:
        key: {{ $secret_key }}
      secretKey: {{ $secret_env_name }}
    {{- end }}
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStoreRef }}
  target:
    creationPolicy: Owner
    name: {{ $target }}
---
{{- end }}
