{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "secretStoreName" . |  quote }}
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.environment.region }}
          clusterName: {{ .Values.environment.cluster_name }}
          clusterProjectID: {{ .Values.environment.project_id }}
          serviceAccountRef:
            name: {{ .Values.environment.service_name }}
      projectID: {{ .Values.secrets.secrets_project }}
{{- end }}