name: Run Jobs for Specific Branch

on:
  workflow_dispatch:
    inputs:
      branches:
        description: "Comma-separated list of branch names"
        required: true
        default: "main,dev"

jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, test, develop] # Define the branches in the matrix

    steps:
      - name: Checkout branch
        uses: ./.github/actions/checkout-branch
        with:
          branch: ${{ matrix.branch }} # Use the current branch from the matrix

      # Add more steps here as needed
      - name: Run tests
        run: |
          echo "Running tests on branch ${{ matrix.branch }}"
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
    #     with:
    #       ref: ${{ matrix.branch-name }}

    #   - name: Display branch name
    #     run: echo "Running on branch ${{ matrix.branch-name }}"

    #   # Add the steps you want to run for each branch here
    #   - name: Run script or command
    #     run: |
    #       echo "Running your script for branch ${{ matrix.branch-name }}"
    #       # Replace with your commands
