name: Dynamic Branch Matrix

on:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Comma-separated list of branches'
        required: true
        default: 'main,develop,feature'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set-branches.outputs.branch-matrix }}
    steps:
      - name: Prepare branch list
        id: set-branches
        run: |
          echo "Creating matrix from input branches"
          branches="${{ github.event.inputs.branches }}"
          branch_array=$(echo "[\"$(echo "$branches" | sed 's/,/\",\"/g')\"]")
          echo "::set-output name=branch-matrix::$branch_array"
  
  print-branches:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.set-matrix.outputs.branches) }}
    steps:
      - name: Print branch name
        run: echo "Branch: ${{ matrix.branch }}"
